create table questionnaire
(
    id                    bigint generated by default as identity
        primary key,
    censored              boolean not null,
    information_id        bigint
        constraint fks5ter2y4vr1mxam3wvkr5noyj
            references information,
    search_information_id bigint
        constraint fkpeu8j9swxvvtrwbeaoymd39kh
            references information,
    user_id               bigint
        constraint fkemxxmaqakd9stj0adwl3h1sot
            references users
);

