create table req_cache
(
    id                bigint generated by default as identity
        primary key,
    factor            double precision not null,
    questionnaire1_id bigint
        constraint fkdwvhn6al9g40t5jtfdyasqxtf
            references questionnaire,
    questionnaire2_id bigint
        constraint fk40or748mqy7a26nyfcxrbvlu4
            references questionnaire
);