--liquibase formatted sql

--changeset lena:user-1
CREATE TABLE  users (
    id BIGSERIAL PRIMARY KEY,
    age INTEGER,
    gender BOOLEAN,
    name TEXT,
    password TEXT,
    role TEXT default 'user'::character varying
)

-- auto-generated definition
-- create table users
-- (
--     id       bigint generated by default as identity
--         primary key,
--     age      integer not null,
--     gender   boolean not null,
--     name     varchar(255),
--     password varchar(255),
--     role     varchar(255) default 'user'::character varying
-- );

